#!/usr/bin/env python3
"""
Interactive script to set up Stripe configuration
"""

import os
from pathlib import Path

def main():
    print("=" * 60)
    print("Stripe Configuration Setup")
    print("=" * 60)
    print()
    print("This script will help you configure Stripe for FutureElite.")
    print("You'll need your Stripe API keys from https://dashboard.stripe.com")
    print()
    
    # Check if .env exists
    env_file = Path('.env')
    if env_file.exists():
        print("⚠️  .env file already exists. This will update it.")
        response = input("Continue? (y/n): ")
        if response.lower() != 'y':
            print("Cancelled.")
            return
    
    print()
    print("Step 1: Get your Stripe API Keys")
    print("-" * 60)
    print("1. Go to https://dashboard.stripe.com")
    print("2. Make sure you're in TEST MODE (toggle in top right)")
    print("3. Go to Developers > API keys")
    print("4. Copy your Publishable key and Secret key")
    print()
    
    stripe_secret = input("Enter your Stripe Secret Key (sk_test_...): ").strip()
    stripe_publishable = input("Enter your Stripe Publishable Key (pk_test_...): ").strip()
    
    print()
    print("Step 2: Create Products in Stripe Dashboard")
    print("-" * 60)
    print("1. Go to Products in Stripe Dashboard")
    print("2. Click 'Add product'")
    print("3. Create 'Monthly Subscription' - $9.99/month recurring")
    print("4. Create 'Annual Subscription' - $99.99/year recurring")
    print("5. Copy the Price ID for each (starts with price_...)")
    print()
    
    monthly_price = input("Enter Monthly Price ID (price_...): ").strip()
    annual_price = input("Enter Annual Price ID (price_...): ").strip()
    
    print()
    print("Step 3: Set up Webhook (Optional for now)")
    print("-" * 60)
    print("You can set up webhooks later. For now, leave this empty.")
    print("When ready, create a webhook endpoint and copy the signing secret.")
    print()
    
    webhook_secret = input("Enter Webhook Secret (whsec_...) or press Enter to skip: ").strip()
    
    # Get or generate secret key
    secret_key = os.environ.get('SECRET_KEY', 'futureelite-2025-dev-only')
    print()
    print(f"Using SECRET_KEY: {secret_key[:20]}...")
    print("(You can change this in .env if needed)")
    
    # Write .env file
    env_content = f"""# Stripe Configuration
# Generated by setup_stripe.py

# Stripe API Keys (Test Mode)
STRIPE_SECRET_KEY={stripe_secret}
STRIPE_PUBLISHABLE_KEY={stripe_publishable}

# Stripe Price IDs
STRIPE_MONTHLY_PRICE_ID={monthly_price}
STRIPE_ANNUAL_PRICE_ID={annual_price}

# Webhook Secret (optional)
STRIPE_WEBHOOK_SECRET={webhook_secret}

# Flask Secret Key
SECRET_KEY={secret_key}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print()
    print("✅ Configuration saved to .env file!")
    print()
    print("Next steps:")
    print("1. Restart the application")
    print("2. Test the subscription flow using test card: 4242 4242 4242 4242")
    print("3. Set up webhook endpoint when ready for production")
    print()
    print("For webhook setup:")
    print("- Endpoint URL: https://yourdomain.com/api/subscription/webhook")
    print("- Events to listen: checkout.session.completed, customer.subscription.*")
    print()

if __name__ == '__main__':
    main()

